# Numpy Library Notebook

The goal of this notebook is to familiarise myself with the common numpy functions so I can become 'fluent' with the functions over time - not always needing to review the documentation.

In [2]:
import numpy as np

# 1. CREATING ARRAYS

In [ ]:
# np.array — make an array from a Python list
a = np.array([1, 2, 3, 4])
print("np.array([1,2,3,4])      ->", a)
 
# 2D array from a list of lists
m = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", m)
 
# np.arange — like range(), but returns an array (start, stop, step)
print("np.arange(0, 10, 2)      ->", np.arange(0, 10, 2))
 
# np.linspace — N evenly spaced points between start and stop (inclusive)
print("np.linspace(0, 1, 5)     ->", np.linspace(0, 1, 5))
 
# np.zeros / np.ones / np.full — arrays pre-filled with a value
print("np.zeros(3)              ->", np.zeros(3))
print("np.ones((2, 2)):\n", np.ones((2, 2)))
print("np.full((2, 2), 7):\n", np.full((2, 2), 7)) #Can also just be done with np.ones((2,2)) * 7

np.array([1,2,3,4])      -> [1 2 3 4]
2D array:
 [[1 2 3]
 [4 5 6]]
np.arange(0, 10, 2)      -> [0 2 4 6 8]
np.linspace(0, 1, 5)     -> [0.   0.25 0.5  0.75 1.  ]
np.zeros(3)              -> [0. 0. 0.]
np.ones((2, 2)):
 [[1. 1.]
 [1. 1.]]
np.full((2, 2), 7):
 [[7 7]
 [7 7]]


# 2. SHAPE & RESHAPING

In [4]:

arr = np.arange(12)
print("arr                      ->", arr)
 
# .shape — dimensions as a tuple (rows, cols, ...)
print("arr.shape                ->", arr.shape)
 
# .reshape — reorganize into new dimensions (must keep total element count)
reshaped = arr.reshape(3, 4)
print("arr.reshape(3, 4):\n", reshaped)
print("reshaped.shape           ->", reshaped.shape)
 
# reshape(-1, n): let numpy infer one dimension (here rows) automatically
print("reshape(-1, 2):\n", arr.reshape(-1, 2))
 
# .ravel / .flatten — collapse back to 1D
print("reshaped.ravel()         ->", reshaped.ravel())
print("reshaped.flatten()       ->", reshaped.flatten())
# (ravel returns a view when possible; flatten always returns a copy)
 
# .T — transpose (swap rows and columns)
print("reshaped.T:\n", reshaped.T)

arr                      -> [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr.shape                -> (12,)
arr.reshape(3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshaped.shape           -> (3, 4)
reshape(-1, 2):
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
reshaped.ravel()         -> [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped.flatten()       -> [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped.T:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# 3. AGGREGATIONS / SUMMARY STATS

In [5]:

data = np.array([4, 8, 15, 16, 23, 42])
print("data                     ->", data)
print("np.mean(data)            ->", np.mean(data))
print("np.median(data)          ->", np.median(data))
print("np.std(data)             ->", np.std(data))     # standard deviation
print("np.var(data)             ->", np.var(data))     # variance (= std**2)
print("np.sum(data)             ->", np.sum(data))
print("np.min(data)             ->", np.min(data))
print("np.max(data)             ->", np.max(data))
# np.percentile — value below which a given % of data falls
print("np.percentile(data, 25)  ->", np.percentile(data, 25))  # 25th pct (Q1)
print("np.percentile(data, 75)  ->", np.percentile(data, 75))  # 75th pct (Q3)

data                     -> [ 4  8 15 16 23 42]
np.mean(data)            -> 18.0
np.median(data)          -> 15.5
np.std(data)             -> 12.315302134607444
np.var(data)             -> 151.66666666666666
np.sum(data)             -> 108
np.min(data)             -> 4
np.max(data)             -> 42
np.percentile(data, 25)  -> 9.75
np.percentile(data, 75)  -> 21.25


# 4. axis=0 vs axis=1 

In [7]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("grid:\n", grid)
# axis=0 collapses ROWS -> result has one value per COLUMN (goes down each column)
print("grid.sum(axis=0)  (down columns) ->", grid.sum(axis=0))   # [1+4, 2+5, 3+6]
# axis=1 collapses COLUMNS -> result has one value per ROW (goes across each row)
print("grid.sum(axis=1)  (across rows)  ->", grid.sum(axis=1))   # [1+2+3, 4+5+6]
print("grid.mean(axis=0)                ->", grid.mean(axis=0))

grid:
 [[1 2 3]
 [4 5 6]]
grid.sum(axis=0)  (down columns) -> [5 7 9]
grid.sum(axis=1)  (across rows)  -> [ 6 15]
grid.mean(axis=0)                -> [2.5 3.5 4.5]


# 5. SORTING & INDEX-FINDING

In [8]:
vals = np.array([30, 10, 50, 20, 40])
print("vals                     ->", vals)
 
# np.sort — returns a sorted copy
print("np.sort(vals)            ->", np.sort(vals))
 
# np.argmin / np.argmax — INDEX of the smallest / largest value
print("np.argmin(vals)          ->", np.argmin(vals), "(index of 10)")
print("np.argmax(vals)          ->", np.argmax(vals), "(index of 50)")
 
# np.argsort — the indices that WOULD sort the array
order = np.argsort(vals)
print("np.argsort(vals)         ->", order)
print("vals[np.argsort(vals)]   ->", vals[order], "(same as np.sort)")

vals                     -> [30 10 50 20 40]
np.sort(vals)            -> [10 20 30 40 50]
np.argmin(vals)          -> 1 (index of 10)
np.argmax(vals)          -> 2 (index of 50)
np.argsort(vals)         -> [1 3 0 4 2]
vals[np.argsort(vals)]   -> [10 20 30 40 50] (same as np.sort)


# 6. BOOLEAN MASKING & np.where

In [9]:
nums = np.array([5, 12, 3, 18, 7, 25])
print("nums                     ->", nums)
 
# A boolean mask: an array of True/False
mask = nums > 10
print("nums > 10                ->", mask)
 
# Use the mask to SELECT elements
print("nums[nums > 10]          ->", nums[nums > 10])
 
# Combine conditions with & (and) / | (or) — parentheses are REQUIRED
print("nums[(nums>5)&(nums<20)] ->", nums[(nums > 5) & (nums < 20)])
 
# np.where(condition, value_if_true, value_if_false)
print("np.where(nums>10,1,0)    ->", np.where(nums > 10, 1, 0))
 
# np.where with one argument returns the INDICES where True
print("np.where(nums>10)[0]     ->", np.where(nums > 10)[0])
 

nums                     -> [ 5 12  3 18  7 25]
nums > 10                -> [False  True False  True False  True]
nums[nums > 10]          -> [12 18 25]
nums[(nums>5)&(nums<20)] -> [12 18  7]
np.where(nums>10,1,0)    -> [0 1 0 1 0 1]
np.where(nums>10)[0]     -> [1 3 5]


# 7. HANDLING NaN / MISSING & INFINITY

In [10]:
with_nan = np.array([1.0, 2.0, np.nan, 4.0, np.inf])
print("with_nan                 ->", with_nan)
 
# np.isnan — True where the value is NaN
print("np.isnan(with_nan)       ->", np.isnan(with_nan))
 
# np.isfinite — True where value is a real finite number (not NaN, not inf)
print("np.isfinite(with_nan)    ->", np.isfinite(with_nan))
 
# Regular mean is contaminated by NaN; nanmean ignores it
print("np.mean(with_nan)        ->", np.mean(with_nan[:4]), "(plain mean of first 4)")
print("np.nanmean(...)          ->", np.nanmean(np.array([1.0, 2.0, np.nan, 4.0])))
 
# Common cleaning idiom: keep only finite values
clean = with_nan[np.isfinite(with_nan)]
print("keep finite only         ->", clean)

with_nan                 -> [ 1.  2. nan  4. inf]
np.isnan(with_nan)       -> [False False  True False False]
np.isfinite(with_nan)    -> [ True  True False  True False]
np.mean(with_nan)        -> nan (plain mean of first 4)
np.nanmean(...)          -> 2.3333333333333335
keep finite only         -> [1. 2. 4.]


# 8. COMBINING ARRAYS

In [11]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
 
# np.concatenate — join along an existing axis (1D here)
print("np.concatenate([x, y])   ->", np.concatenate([x, y]))
 
# np.vstack — stack vertically (row on top of row) -> 2D
print("np.vstack([x, y]):\n", np.vstack([x, y]))
 
# np.hstack — stack horizontally (end to end)
print("np.hstack([x, y])        ->", np.hstack([x, y]))
 
# np.stack — join along a NEW axis (creates an extra dimension)
print("np.stack([x, y]):\n", np.stack([x, y]))
print("np.stack shape           ->", np.stack([x, y]).shape)

np.concatenate([x, y])   -> [1 2 3 4 5 6]
np.vstack([x, y]):
 [[1 2 3]
 [4 5 6]]
np.hstack([x, y])        -> [1 2 3 4 5 6]
np.stack([x, y]):
 [[1 2 3]
 [4 5 6]]
np.stack shape           -> (2, 3)


# 9. LINEAR ALGEBRA

In [12]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print("A:\n", A)
print("B:\n", B)
 
# np.dot / @  — matrix multiplication (NOT element-wise)
print("np.dot(A, B):\n", np.dot(A, B))
print("A @ B  (same thing):\n", A @ B)
 
# For contrast: * is ELEMENT-WISE multiplication
print("A * B  (element-wise):\n", A * B)
 
# np.linalg.inv — matrix inverse
inv = np.linalg.inv(A)
print("np.linalg.inv(A):\n", inv)
print("A @ inv (=identity):\n", np.round(A @ inv, 10))
 
# np.linalg.norm — vector length (Euclidean by default)
v = np.array([3, 4])
print("np.linalg.norm([3,4])    ->", np.linalg.norm(v), "(the 3-4-5 triangle)")

A:
 [[1 2]
 [3 4]]
B:
 [[5 6]
 [7 8]]
np.dot(A, B):
 [[19 22]
 [43 50]]
A @ B  (same thing):
 [[19 22]
 [43 50]]
A * B  (element-wise):
 [[ 5 12]
 [21 32]]
np.linalg.inv(A):
 [[-2.   1. ]
 [ 1.5 -0.5]]
A @ inv (=identity):
 [[1. 0.]
 [0. 1.]]
np.linalg.norm([3,4])    -> 5.0 (the 3-4-5 triangle)


# 10. BROADCASTING

In [13]:
# Broadcasting = numpy auto-expands smaller shapes to match bigger ones.
 
vec = np.array([1, 2, 3])
print("vec                      ->", vec)
 
# scalar broadcasts across the whole array
print("vec + 10                 ->", vec + 10)
print("vec * 2                  ->", vec * 2)
 
# a (3,1) column plus a (3,) row -> (3,3) grid
col = np.array([[10], [20], [30]])
print("col:\n", col)
print("col + vec  (3x1 + 1x3 -> 3x3):\n", col + vec)

vec                      -> [1 2 3]
vec + 10                 -> [11 12 13]
vec * 2                  -> [2 4 6]
col:
 [[10]
 [20]
 [30]]
col + vec  (3x1 + 1x3 -> 3x3):
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


# 11. RANDOM NUMBERS

In [ ]:
#  np.random.seed — fixes the generator so results are REPRODUCIBLE.
# Always set this in an assessment so your output matches on re-run.
np.random.seed(42)
 
# np.random.rand — uniform floats in [0, 1)
print("np.random.rand(3)        ->", np.random.rand(3))
 
# np.random.randn — standard normal (mean 0, std 1)
print("np.random.randn(3)       ->", np.random.randn(3))
 
# np.random.randint — random integers (low inclusive, high exclusive)
print("np.random.randint(0,10,5)->", np.random.randint(0, 10, 5))
 
# np.random.choice — sample from a set of values
print("np.random.choice(...)    ->", np.random.choice(['a', 'b', 'c'], size=4))
 
# Reproducibility demo: same seed -> same numbers every time
np.random.seed(42)
first = np.random.rand(2)
np.random.seed(42)
second = np.random.rand(2)
print("seed(42) run 1           ->", first)
print("seed(42) run 2           ->", second, "(identical -> reproducible)")

np.random.rand(3)        -> [0.37454012 0.95071431 0.73199394]
np.random.randn(3)       -> [-1.11188012  0.31890218  0.27904129]
np.random.randint(0,10,5)-> [7 2 5 4 1]
np.random.choice(...)    -> ['b' 'b' 'b' 'a']
seed(42) run 1           -> [0.37454012 0.95071431]
seed(42) run 2           -> [0.37454012 0.95071431] (identical -> reproducible)

Done. Every function above is on your cheat sheet.
